services:
  unitree_ros:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        INSTALL_COCO: ${INSTALL_COCO:-false}
        INSTALL_CPP_LIDAR: ${INSTALL_CPP_LIDAR:-false}
        INSTALL_FULL_STACK: ${INSTALL_FULL_STACK:-false}
    environment:
      ROBOT_IP: ${ROBOT_IP:-}
      CONN_TYPE: ${CONN_TYPE:-webrtc}
      WEBRTC_SERVER_HOST: 0.0.0.0
      WEBRTC_SERVER_PORT: ${WEBRTC_SERVER_PORT:-9991}
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    network_mode: host
    restart: "no"
